### ISSUE TITLE
Can't run on executable on ps3

### ISSUE THREAD

**Issue by kabone** [ps3dev/ps3dev-docker#2]
Hello, I followed all the steps but when i run a simple hello world application in c and try to run it in red ribbon I get a segmentation error. Do I need to build on a ppc64 like the psl1ght repo says? Or does this docker not need ppc64? The host running docker is Intel x64. Any help would be greatly appreciated.

**Comment by zeldin** [comment]
Are you having trouble running the docker itself, or trouble running the binaries you compile in the docker on the ps3? I have no idea what a "red ribbon" is...

For the docker, a prebuilt docker will only run on the same arch that it was built on.  That is just how docker works.  So if you pull down the one I posted on docker.com, you will need ppc64 to run it because that's what it was built on.  But if you build the docker yourself using "docker build" then it should run on the same machine that you built it on.

If you are successful in compiling some ps3 application with the docker but unable to run it, what environment are you testing it in?  PS3 Linux?  PSL1GHT applications are meant to run under GameOS (which does not show "segmentation error" to the user)...

**Comment by kabone** [comment]
> Are you having trouble running the docker itself, or trouble running the binaries you compile in the docker on the ps3? I have no idea what a "red ribbon" is...
> 
> For the docker, a prebuilt docker will only run on the same arch that it was built on. That is just how docker works. So if you pull down the one I posted on docker.com, you will need ppc64 to run it because that's what it was built on. But if you build the docker yourself using "docker build" then it should run on the same machine that you built it on.
> 
> If you are successful in compiling some ps3 application with the docker but unable to run it, what environment are you testing it in? PS3 Linux? PSL1GHT applications are meant to run under GameOS (which does not show "segmentation error" to the user)...

I used `docker build -t ps3dev-docker .`  I was able to compile the binaries successfully when I changed the flags in my Makefile to `ppu-gcc` instead of `gcc`. I was running in a ps3 linux distro, but as you said it's meant for gameOS i tried that. 



```
#include <stdio.h>
int main(void)
{
   printf ("Hello from your first program!\n%s");
   return 0;
}
```

```
CC      = ppu-gcc
CFLAGS  = -g
#RM      = rm -f


default: all

all: hello

hello: hello.c
        $(CC) $(CFLAGS) -o hello hello.c

clean veryclean:
        $(RM) hello
```






I ran:
`ps3dev-docker.sh make`
which gives me the binary. 

but when I run it in gameOS on CFW i get:
```
80029563
```

**Comment by zeldin** [comment]
> ```
> #include <stdio.h>
> int main(void)
> {
>    printf ("Hello from your first program!\n%s");
>    return 0;
> }
> ```
You have specified a "%s" conversion without providing the corresponding string pointer argument.  This will most likely cause a crash no matter what environment you run under.  :smiley: 

You might want to try out some example programs from the ``samples`` folder of PSL1GHT to start off with known working programs.

**Comment by kabone** [comment]
Half of the ` samples` won't compile. The ones that do compile give errors as well.
